[package]
name = "sdflit"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sdflit"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.0"
numpy = "0.20"
pyo3 = "0.20.0"
rand = "0.8.5"
