[package]
name = "sdflit"
version = "0.2.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sdflit"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.27.1"
pyo3 = "0.27.2"
rand = "0.8.5"
